services:
    _defaults:
        autowire: true
        autoconfigure: true

    wooppay\YiiToSymfonyValidatorsBundle\:
        resource: '../../../src/*'
        exclude: '../../../src/{DependencyInjection,Entity,Tests,Kernel.php}'